server:
  port: 8765

spring:
  application:
    name: service-feign

eureka:
  client:
    service-Url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}