server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master # 配置仓库分支，不写则默认为master
      server:
        git:
          uri: https://gitee.com/threshold/spring-cloud-config-repository # 配置Git仓库地址
          searchPaths: repository # 配置仓库路径
          password: '' # 用户名（公开仓库则不需要用户名和密码，私有仓库需要指定）
          username: '' # 密码